<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ArtistDetail.aspx.cs" Inherits="KpopZtation.View.ArtistDetail" enableEventValidation="false"%>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="lblname" runat="server" Text="Artist Name"></asp:Label>
            <asp:Label ID="dname" runat="server" Text=""></asp:Label>
            <br />
            <asp:Label ID="lblimage" runat="server" Text="Artist Image"></asp:Label>
            <asp:Label ID="dimage" runat="server" Text=""></asp:Label>

            <asp:GridView ID="albumGV" runat="server" AutoGenerateEditButton="false" AutoGenerateDeleteButton="true" OnRowEditing="albumGV_RowEditing" OnRowDeleting="albumGV_RowDeleting">
                <Columns>
        
                    <asp:CommandField ButtonType="Button" ShowEditButton="true" EditText="Update"/>
                  <asp:TemplateField>
                    <ItemTemplate>
                        <asp:Button ID="btncard" runat="server" Text="CARD" onclick="btncard_Click"/>
                     </ItemTemplate>
                    </asp:TemplateField>

            </Columns>
            </asp:GridView>
            <asp:Button ID="btninsert" runat="server" Text="Insert Album" onclick="btninsert_Click"/>
        </div>
    </form>
</body>
</html>
